### ISSUE TITLE
Not Supporting with jQuery 1.9 and jQuery UI 1.10.4

### ISSUE THREAD

**Issue by sathishchandrasanga** [ehynds/jquery-ui-multiselect-widget#575] opened 2014-10-01 00:15 UTC
Thanks for nice plugin,It was working fine with jQuery 1.7 and jquery ui 1.8 .Recently we have upgraded to jquery 1.9 and jQuery UI 1.10.4.Its not working and throwing this below error

Uncaught Error: cannot call methods on multiselect prior to initialization; attempted to call method 'destroy' jquery-1.9.0.js:490jQuery.extend.error jquery-1.9.0.js:490(anonymous function) jquery-ui-1.10.4.custom.min.js:6jQuery.extend.each jquery-1.9.0.js:631jQuery.fn.jQuery.each jquery-1.9.0.js:253e.fn.(anonymous function) jquery-ui-1.10.4.custom.min.js:6populateDropDown using.js:248(anonymous function) using.htm:1105fire jquery-1.9.0.js:1017self.fireWith jquery-1.9.0.js:1127jQuery.extend.ready jquery-1.9.0.js:416DOMContentLoaded jquery-1.9.0.js:92

**Comment by Gwasshoppa** [comment] 2015-04-13 03:45
I dont have an issue with jquery 1.11.4... although the filter plug in is not allowing a user to click into the filter textbox.

**Comment by mlh758** [comment] 2016-03-15 15:22
I've been able to test this plugin all the way up through jQuery 2.x and the latest jQuery UI. Are you still experiencing issues?

The unit tests are all passing as well now with the latest of both libraries in use.

**Comment by Gwasshoppa** [comment] 2016-03-15 19:53
Sorry we are not using this any more so Im not sure whether this is still an issue.

**Comment by mlh758** [comment] 2016-03-15 20:01
Okay, I'm going to go ahead and close this then due to the issue's age and being unable to reproduce it.

**Closed by mlh758** 2016-03-15 20:01 UTC

**Comment by joeller** [comment] 2016-03-16 06:01
I tried to connect link below to see which issue this was concerning
but the browser would not display the link.

Can you give me a hint want this  was about?

On 3/15/16, Michael <notifications@github.com> wrote:
> I've been able to test this plugin all the way up through jQuery 2.x and the
> latest jQuery UI. Are you still experiencing issues?
>
> The unit tests are all passing as well now with the latest of both libraries
> in use.
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ehynds/jquery-ui-multiselect-widget/issues/575#issuecomment-196874472


-- 
Edward R. Joell
Indian Head, MD

**Comment by mlh758** [comment] 2016-03-16 13:12
@joeller this was a compatibility issue regarding jQuery 1.9 and jQuery UI multiselect.

**Comment by joeller** [comment] 2016-03-16 13:45
But you said you had no issues?    Hmmmm.

For reasons I don't want to take time to go into at this time, I have both
1.8.2 and 1.11.x in my project.  If it is the one I am thinking about, I
have not experienced any issue yet.  However we are looking to upgrade our
JQuery in the near future to the latest one.  Do you think we will have any
issues with this tool?

Edward R. Joell
Indian Head, MD

**Comment by mlh758** [comment] 2016-03-16 13:57
I recently updated the unit tests to run on the latest jQuery and jQuery UI libraries available from https://developers.google.com/speed/libraries/

All the tests pass, no errors are thrown in the console. I haven't seen any issues so far.
