### ISSUE TITLE
IE10 post data broken in compatibility mode

### ISSUE THREAD

**Issue by KAnderson** [ehynds/jquery-ui-multiselect-widget#453] opened 2013-05-09 16:08 UTC
When opening my website in compatibility mode (which it defaults to in IE 10 for intranet sites) the values passed to the post method are messed up. It set's the widget so that all the items are 'Checked'.

**Comment by mlh758** [comment] 2017-02-07 14:19
I haven't been able to reproduce this, and the issue is from 2013 so I'm going to close it for now.

**Closed by mlh758** 2017-02-07 14:19 UTC
