### ISSUE TITLE
vertical scroll after reload of page

### ISSUE THREAD

**Issue by sri3236** [ehynds/jquery-ui-multiselect-widget#594] opened 2015-01-20 09:07 UTC
Hello,

Am getting vertical scroll bar of filter part  to left of the page when i reload. Please find the attached pic. I have other screens where there is no issue, but for only one screen am facing this issue.

![1](https://cloud.githubusercontent.com/assets/10611390/5814484/f419f26c-a0b1-11e4-9d4b-358f6be4568f.jpg)

**Comment by mlh758** [comment] 2016-03-15 20:04
Closing this issue due to the age, lack of information to reproduce, and no similar issues reported.

If you're still having this problem let me know and I will reopen the issue.

**Closed by mlh758** 2016-03-15 20:04 UTC
