### ISSUE TITLE
Checkbox need for option group along with elements

### ISSUE THREAD

**Issue by 1979kiran** [ehynds/jquery-ui-multiselect-widget#359] opened 2013-01-02 11:11 UTC
Hi,

This a great plugin, i liked it alot but only issue i noticed isthecheck box  next to optgroup label is missing.  Can you please include clickable checkbox for option group header label  that will visually help users to understand better when they click on optgroup they can see checkbox selected along with child elements checkbox checked.

kindly let me know if you have any patch for this already.

Bests
Kiran
Chennai, India

**Comment by mlh758** [comment] 2017-01-06 17:34
Closing as a duplicate of #284

**Closed by mlh758** 2017-01-06 17:34 UTC
