### ISSUE TITLE
Textarea text disappears while typing after selecting options from multiSelect

### ISSUE THREAD

**Issue by evapisces** [ehynds/jquery-ui-multiselect-widget#528] opened 2014-01-24 14:56 UTC
I have two multiSelects on my page, the second one is populated based on selection(s) from the first one. I also have three textareas on the same page. My issue occurs as follows:
1. Select option(s) from the first dropdown
2. Select option(s) from the second dropdown
3. Immediately click in the first textarea and start typing. As I'm typing in the textarea, the text continually disappears.
For example, if I type the word "Test," the letters "Te" appear and quickly disappear. Then the letters "st" appear and quickly disappear, and the cycle continues.

The issue only occurs when I go straight from the second dropdown to the textarea. If I click somewhere else on the page after selecting from the dropdown and before going to the textarea, everything works fine (no text disappears).

Any help with this would be greatly appreciated.
Thanks!

**Comment by mlh758** [comment] 2017-01-03 19:00
Closing this due to age and how specific the issue is.

**Closed by mlh758** 2017-01-03 19:00 UTC
