### ISSUE TITLE
Version 2.x vs 1.13, option results.

### ISSUE THREAD

**Issue by hekep** [ehynds/jquery-ui-multiselect-widget#694] opened 2017-04-07 07:45 UTC
In version 1.13 all options were available, user does not have to use  filter search field.

In version 2.x all options are hidden by default, user has to use filter search field, and provide at least on character.  

How make all options visibile in 2.x. User does not want to use search field.

**Comment by mlh758** [comment] 2017-04-07 11:35
That's not something I see happening. Can you provide a fiddle?

**Comment by mlh758** [comment] 2017-05-31 21:50
Closing since I can't reproduce and it's been a couple of months.

**Closed by mlh758** 2017-05-31 21:50 UTC
