### ISSUE TITLE
Multiselect menus won't close with jQuery 1.8.3/jQuery UI 1.9.2

### ISSUE THREAD

**Issue by devrap** [ehynds/jquery-ui-multiselect-widget#450] opened 2013-05-02 23:42 UTC
After upgrading WP and Buddypress on our development site, which uses jQuery 1.8.3/jQuery UI 1.9.2, this causes an error when using multiselect on one of our forms. The menus will not collapse/lose focus when clicking away or clicking on the close button.

Please see http://test3.gaylesta.org or http://test3.gaylesta.org/locate-a-therapist/ for an example (click on "Area of Focus" or "Therapy Type" to see the problem in action).

In my console, clicking on a menu reports this error on /js/jquery.js:
uncaught typeerror: property '400' of object # is not a function

Multiselect menus work fine on our old/not yet updated live site, running jQuery 1.7.1/jQuery UI 1.8.16

I'm using jQuery MultiSelect UI Widget 1.14pre--which I updated to-- which uses pretty old jQuery (1.4.2) and jQuery UI (1.8), and am suspecting old syntax may be the issue. Any updates coming, or any clues on how I can update jquery.multiselect.js to fix this error? Many thanks.

Also, I notice this thread in which you recommend upgrading to a "master widget," which I also can't find here. https://github.com/ehynds/jquery-ui-multiselect-widget/issues/421

**Comment by mlh758** [comment] 2017-01-10 19:55
The master version of the widget just means use the version of the widget from the [master branch](https://github.com/ehynds/jquery-ui-multiselect-widget).

I haven't had any other reports of this issue happening and I can't reproduce so given the age and the number of updates since I'm doing to close this.

**Closed by mlh758** 2017-01-10 19:55 UTC
